# Generated by Django 5.2 on 2025-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_tracking',
            name='st_act',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock_tracking',
            name='st_prev',
            field=models.IntegerField(null=True),
        ),
    ]
