# Generated by Django 5.2 on 2025-04-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_stock_tracking_st_act_stock_tracking_st_prev'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
