# Generated by Django 5.2 on 2025-04-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
