# Generated by Django 5.2 on 2025-04-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='positions',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.DeleteModel(
            name='stock_tracking',
        ),
        migrations.DeleteModel(
            name='supliers',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
