# Generated by Django 5.2 on 2025-04-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0008_delete_categories_delete_items_delete_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='supliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='nombre')),
                ('user_name', models.CharField(max_length=100)),
                ('user_availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_tracking',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_prev', models.IntegerField(null=True)),
                ('st_act', models.IntegerField(null=True)),
                ('st_id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.stock')),
                ('st_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.users')),
            ],
        ),
    ]
