# Generated by Django 5.2 on 2025-04-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='positions',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_stock',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_user',
        ),
        migrations.DeleteModel(
            name='supliers',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.DeleteModel(
            name='stock_tracking',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
