# Generated by Django 5.2 on 2025-04-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_category_id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_suplier_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_item_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_position_id',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_stock',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_user',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='supliers',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='positions',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.DeleteModel(
            name='stock_tracking',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
