# Generated by Django 5.2 on 2025-04-29 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0014_remove_items_item_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='posicione',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('posotion_index', models.PositiveIntegerField()),
                ('position_aviable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('suplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('suplier_name', models.CharField(max_length=50, verbose_name='nombre')),
                ('suplier_address', models.CharField(max_length=100)),
                ('suplier_Tel', models.PositiveIntegerField()),
                ('suplier_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='nombre')),
                ('user_password', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=100)),
                ('user_availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50, verbose_name='producto')),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.categoria')),
                ('item_suplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.provedor')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_deseado', models.SmallIntegerField()),
                ('stock_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.productos')),
                ('stock_position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.posicione')),
            ],
        ),
        migrations.CreateModel(
            name='stock_tracking',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_prev', models.IntegerField(null=True)),
                ('st_act', models.IntegerField(null=True)),
                ('st_id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.stock')),
                ('st_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.usuarios')),
            ],
        ),
    ]
