# Generated by Django 5.2 on 2025-04-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_itme_amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='item_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='item_suplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.provedor', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='suplier_Tel',
            field=models.PositiveIntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='suplier_address',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='suplier_owner',
            field=models.CharField(max_length=50, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_deseado',
            field=models.SmallIntegerField(verbose_name='Nesesarios'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.productos', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.posicione', verbose_name='posicion'),
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_act',
            field=models.IntegerField(default=0, verbose_name='Stock nuevo'),
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_id_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.stock', verbose_name='Stock del Producto'),
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.usuarios', verbose_name='Quien hace el movimiento'),
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_prev',
            field=models.IntegerField(default=0, verbose_name='Stock anterior'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_availability',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_password',
            field=models.CharField(max_length=8, verbose_name='Contraseña'),
        ),
    ]
