# Generated by Django 5.2 on 2025-04-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_stock_stock_itme_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='item_category_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_position_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='item_suplier_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_item_id',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_stock',
        ),
        migrations.RemoveField(
            model_name='stock_tracking',
            name='st_id_user',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='posicione',
        ),
        migrations.DeleteModel(
            name='Provedor',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.DeleteModel(
            name='stock_tracking',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
