# Generated by Django 5.2 on 2025-04-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0017_remove_productos_item_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='posicione',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('posotion_index', models.PositiveIntegerField()),
                ('position_aviable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('suplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('suplier_name', models.CharField(max_length=50, verbose_name='nombre')),
                ('suplier_address', models.CharField(max_length=100, verbose_name='Email')),
                ('suplier_Tel', models.IntegerField(verbose_name='Celular')),
                ('suplier_owner', models.CharField(max_length=50, verbose_name='Encargado')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('user_availability', models.BooleanField(verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='producto')),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.categoria', verbose_name='categoria')),
                ('item_suplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.provedor', verbose_name='Provedor')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_itme_amount', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('stock_deseado', models.SmallIntegerField(verbose_name='Nesesarios')),
                ('stock_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.productos', verbose_name='producto')),
                ('stock_position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.posicione', verbose_name='posicion')),
            ],
        ),
        migrations.CreateModel(
            name='stock_tracking',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('st_prev', models.IntegerField(default=0, verbose_name='Stock anterior')),
                ('st_act', models.IntegerField(default=0, verbose_name='Stock nuevo')),
                ('st_id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.stock', verbose_name='Stock del Producto')),
                ('st_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.usuarios', verbose_name='Quien hace el movimiento')),
            ],
        ),
    ]
