# Generated by Django 5.2 on 2025-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_act',
            field=models.IntegerField(verbose_name='Stock nuevo'),
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_prev',
            field=models.IntegerField(verbose_name='Stock anterior'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_availability',
            field=models.BooleanField(verbose_name='Activo'),
        ),
    ]
