# Generated by Django 5.2 on 2025-09-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_stock_tracking_st_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('suplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('suplier_name', models.CharField(max_length=50, verbose_name='nombre')),
                ('suplier_address', models.CharField(max_length=100, verbose_name='Email')),
                ('suplier_tel', models.IntegerField(verbose_name='Celular')),
                ('suplier_owner', models.CharField(max_length=50, verbose_name='Encargado')),
            ],
        ),
        migrations.RenameModel(
            old_name='posicione',
            new_name='positions',
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='item_category_id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='item_suplier_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_itme_amount',
            new_name='stock_item_amount',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_deseado',
            new_name='stock_wanted',
        ),
        migrations.RenameModel(
            old_name='categoria',
            new_name='categories',
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='producto')),
                ('item_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.categories', verbose_name='Categoria')),
                ('item_suplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.suppliers', verbose_name='Proveedor')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.items', verbose_name='producto'),
        ),
        migrations.DeleteModel(
            name='Provedor',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
