# Generated by Django 5.2 on 2025-10-03 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_suppliers_rename_posicione_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_tracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha del movimiento'),
            preserve_default=False,
        ),
    ]
