# Generated by Django 5.2 on 2025-10-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_customuser_alter_stock_tracking_st_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('user_password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('user_availability', models.BooleanField(verbose_name='Activo')),
            ],
        ),
        migrations.AlterField(
            model_name='stock_tracking',
            name='st_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.users', verbose_name='Quien hace el movimiento'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
